
a = [1,2,3]

try:
    a[5]
except:
    print("capturei exception")
finally:
    print("entrando no finally")
